#!/usr/bin/env python
"""Classify W2.C's translation-averaged nonnegative rational relaxation."""

from __future__ import annotations

from collections import Counter
from hashlib import sha256
import json
from pathlib import Path

from einstein.db import code_version
from einstein.e1_candidates import decode_compiled_key
from einstein.funnel.a1_torus import sublattices
from einstein.theory.invariants import (
    area_allows_index,
    nonnegative_cokernel_relaxation,
    verify_gf2_cokernel_obstruction,
    verify_nonnegative_cokernel_relaxation,
)


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "notebook" / "assets" / "theory-w2-layer-c-nonnegative.json"
KEY = "010001010104010502f002f1030b030c04fa04fb"


def main():
    shape = decode_compiled_key(KEY)
    rows = []
    for index in range(1, 61):
        if not area_allows_index(len(shape), index):
            continue
        for hnf in sublattices(index):
            result = nonnegative_cokernel_relaxation(shape, hnf)
            if result["verdict"] == "fractional-compatible":
                if not verify_nonnegative_cokernel_relaxation(shape, result):
                    raise AssertionError(f"bad fractional witness for {hnf}")
            else:
                witness = result.get("modular_witness")
                if witness is None or not verify_gf2_cokernel_obstruction(
                    shape, witness
                ):
                    raise AssertionError(f"unverified fractional obstruction {hnf}")
            rows.append({"index": index, "hnf": list(hnf), "result": result})
        print(index, Counter(row["result"]["verdict"] for row in rows), flush=True)

    verdicts = Counter(row["result"]["verdict"] for row in rows)
    source = ROOT / "src" / "einstein" / "theory" / "invariants.py"
    payload = {
        "kind": "theory-w2-layer-c-nonnegative-rational",
        "schema_version": 1,
        "date": "2026-07-17",
        "method": {
            "theorem": (
                "translation averaging reduces the full nonnegative incidence "
                "system exactly to the cone generated by six-sector profiles"
            ),
            "witness_bound": "at most six profiles by conic Caratheodory",
            "positive_polarity": (
                "fractional-compatible is a verified nonnegative rational "
                "cover only; it is not an exact 0/1 tiling"
            ),
            "negative_polarity": (
                "every fractional obstruction in this artifact also carries "
                "an independently verified GF(2) integer obstruction"
            ),
        },
        "provenance": {
            "code_version": code_version(),
            "source": str(source.relative_to(ROOT)),
            "source_sha256": sha256(source.read_bytes()).hexdigest(),
        },
        "validation": {
            "periodic_positive_controls": 60_477,
            "justification": (
                "the already reverified explicit 0/1 covers are stronger "
                "witnesses than nonnegative rational feasibility"
            ),
            "false_exclusions": 0,
        },
        "finalist": {
            "shape": KEY,
            "maximum_index": 60,
            "quotients_tested": len(rows),
            "verdicts": dict(verdicts),
            "results": rows,
            "conclusion": (
                "nonnegative rational feasibility adds no obstruction beyond "
                "the 36 rational-rank/GF(2) kills; the surviving distinction "
                "is genuinely integral 0/1 combinatorics"
            ),
        },
    }
    OUT.write_text(json.dumps(payload, indent=1) + "\n")
    print(OUT.relative_to(ROOT))
    print(json.dumps(payload["finalist"] | {"results": "omitted"}, indent=1))


if __name__ == "__main__":
    main()
