"""Exact reference transfer automaton for a fixed cylinder period.

For a nonzero lattice vector ``v``, quotient the kite grid by ``<v>`` and
sweep it one transverse lattice column at a time.  A state records the cells
in future columns already occupied by whole tile placements crossing the cut.
All possible crossing-state unions are enumerated, rather than only states
reachable from an empty cut.  This distinction is essential: a valid tiling
may cross every cut.

The implementation is deliberately finite and simple.  It is a correctness
reference for small cylinders, not yet the optimized W1 engine.  Resource
limits have no mathematical polarity and return ``resource-exhausted``.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
import math
from typing import Iterable

from einstein.polykites.periodic_quotients import (
    cell_to_lattice,
    lattice_to_cell,
    verify_certificate,
)
from einstein.geometry.kite_grid import N_OPS, transform_cell

Cell = tuple[int, int, int]
Vector = tuple[int, int]
State = tuple[int, ...]


class TransferLimit(RuntimeError):
    """A declared reference-engine resource bound was reached."""


@dataclass(frozen=True)
class Pattern:
    """One placement introduced at its minimum transverse column."""

    op: int
    alpha: int
    min_beta: int
    masks: tuple[int, ...]


@dataclass(frozen=True)
class Edge:
    source: State
    target: State
    patterns: tuple[int, ...]


@dataclass
class TransferResult:
    verdict: str
    vector: Vector
    primitive: Vector
    multiplicity: int
    transverse: Vector
    state_count: int
    edge_count: int
    interaction_span: int
    graph_sha256: str | None = None
    cycle: tuple[Edge, ...] | None = None
    certificate: dict | None = None
    limit: dict | None = None

    def summary(self) -> dict:
        return {
            "kind": "cylinder-transfer",
            "verdict": self.verdict,
            "vector": list(self.vector),
            "primitive": list(self.primitive),
            "multiplicity": self.multiplicity,
            "transverse": list(self.transverse),
            "state_count": self.state_count,
            "edge_count": self.edge_count,
            "interaction_span": self.interaction_span,
            "graph_sha256": self.graph_sha256,
            "cycle_length": len(self.cycle) if self.cycle else None,
            "certificate": self.certificate,
            "limit": self.limit,
        }


def _extended_gcd(a: int, b: int) -> tuple[int, int, int]:
    """Return positive gcd and coefficients ``x*a + y*b = gcd``."""
    old_r, r = abs(a), abs(b)
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    x = old_s if a >= 0 else -old_s
    y = old_t if b >= 0 else -old_t
    return old_r, x, y


def cylinder_basis(vector: Vector) -> tuple[Vector, int, Vector]:
    """Return primitive ``p``, ``g`` and ``u`` with ``v=g*p``, det(p,u)=1."""
    x, y = vector
    g = math.gcd(abs(x), abs(y))
    if g == 0:
        raise ValueError("period vector must be nonzero")
    p = (x // g, y // g)
    gcd, a, b = _extended_gcd(p[0], p[1])
    assert gcd == 1
    # p.x*a + p.y*b = 1, hence det(p, (-b,a)) = 1.
    u = (-b, a)
    assert p[0] * u[1] - p[1] * u[0] == 1
    return p, g, u


def basis_coordinates(q: Vector, p: Vector, u: Vector) -> tuple[int, int]:
    """Coordinates ``q=alpha*p+beta*u`` for the unimodular basis (p,u)."""
    alpha = q[0] * u[1] - q[1] * u[0]
    beta = p[0] * q[1] - p[1] * q[0]
    return alpha, beta


def lattice_hnf(v: Vector, w: Vector) -> tuple[int, int, int]:
    """Canonical A1 HNF ``(a,b,d)`` for the lattice generated by v,w."""
    det = v[0] * w[1] - v[1] * w[0]
    if det == 0:
        raise ValueError("period generators must be independent")
    d, r, s = _extended_gcd(v[1], w[1])
    if d == 0:
        raise ValueError("independent generators cannot both have y=0")
    a = abs(det) // d
    b = (r * v[0] + s * w[0]) % a
    return a, b, d


def vector_norm2(vector: Vector) -> int:
    """Center-lattice norm up to the common physical factor 12."""
    x, y = vector
    return x * x + x * y + y * y


def vector_orbit(vector: Vector) -> tuple[Vector, ...]:
    """Exact D6 orbit of a nonzero center-lattice vector."""
    if vector == (0, 0):
        raise ValueError("period vector must be nonzero")
    cell = lattice_to_cell((vector[0], vector[1], 0))
    orbit = set()
    for op in range(N_OPS):
        x, y, _ = cell_to_lattice(transform_cell(cell, op))
        orbit.add((x, y))
    return tuple(sorted(orbit))


def vector_orbit_representatives(max_norm2: int) -> tuple[Vector, ...]:
    """One stable representative of every nonzero D6 orbit with Q(v)<=N."""
    if max_norm2 < 1:
        return ()
    # Q(x,y) >= (x^2+y^2)/2, so this square safely contains the norm ball.
    bound = math.isqrt(2 * max_norm2) + 1
    unseen = {
        (x, y)
        for x in range(-bound, bound + 1)
        for y in range(-bound, bound + 1)
        if (x or y) and vector_norm2((x, y)) <= max_norm2
    }
    representatives = []
    while unseen:
        seed = min(unseen)
        orbit = set(vector_orbit(seed))
        candidates = [v for v in orbit if v[0] >= v[1] >= 0]
        representative = min(candidates or orbit)
        representatives.append(representative)
        unseen -= orbit
    return tuple(sorted(representatives, key=lambda v: (vector_norm2(v), v)))


class CylinderTransfer:
    """Compile and decide the exact transfer graph for ``shape`` and ``v``."""

    def __init__(
        self,
        shape: Iterable[Cell],
        vector: Vector,
        *,
        max_states: int = 200_000,
        max_edges: int = 2_000_000,
    ):
        self.shape = tuple(tuple(c) for c in shape)
        if not self.shape:
            raise ValueError("shape must contain at least one kite")
        self.vector = tuple(vector)
        self.p, self.g, self.u = cylinder_basis(self.vector)
        self.layer_size = 6 * self.g
        self.full_layer = (1 << self.layer_size) - 1
        self.max_states = max_states
        self.max_edges = max_edges
        self.patterns, self.span = self._compile_patterns()

    def _compile_patterns(self) -> tuple[tuple[Pattern, ...], int]:
        raw = []
        max_span = 0
        for op in range(N_OPS):
            image = [cell_to_lattice(transform_cell(c, op)) for c in self.shape]
            coords = []
            for x, y, sector in image:
                alpha, beta = basis_coordinates((x, y), self.p, self.u)
                coords.append((alpha, beta, sector))
            min_beta = min(beta for _, beta, _ in coords)
            max_beta = max(beta for _, beta, _ in coords)
            span = max_beta - min_beta
            max_span = max(max_span, span)
            for shift in range(self.g):
                cells = {
                    (beta - min_beta, ((alpha + shift) % self.g) * 6 + sector)
                    for alpha, beta, sector in coords
                }
                # A placement that identifies two of its own cells modulo v is
                # invalid on the cylinder.
                if len(cells) != len(coords):
                    continue
                raw.append((op, shift, min_beta, cells))

        by_masks: dict[tuple[int, ...], Pattern] = {}
        for op, shift, min_beta, cells in raw:
            masks = [0] * (max_span + 1)
            for layer, bit in cells:
                masks[layer] |= 1 << bit
            key = tuple(masks)
            by_masks.setdefault(key, Pattern(op, shift, min_beta, key))
        patterns = tuple(by_masks[key] for key in sorted(by_masks))
        return patterns, max_span

    @staticmethod
    def _disjoint(left: State, right: State) -> bool:
        return all(not (a & b) for a, b in zip(left, right))

    def _crossing_contributions(self) -> tuple[State, ...]:
        if self.span == 0:
            return ()
        contributions = set()
        for pattern in self.patterns:
            last = max(i for i, mask in enumerate(pattern.masks) if mask)
            for age in range(1, self.span + 1):
                if last < age:
                    continue
                masks = tuple(
                    pattern.masks[layer + age]
                    if layer + age < len(pattern.masks)
                    else 0
                    for layer in range(self.span)
                )
                if any(masks):
                    contributions.add(masks)
        return tuple(sorted(contributions))

    def enumerate_states(self) -> tuple[State, ...]:
        """Enumerate every nonoverlapping union of cut-crossing contributions."""
        zero = (0,) * self.span
        states = {zero}
        for contribution in self._crossing_contributions():
            additions = []
            for state in states:
                if self._disjoint(state, contribution):
                    additions.append(tuple(a | b for a, b in zip(state, contribution)))
            states.update(additions)
            if len(states) > self.max_states:
                raise TransferLimit(
                    f"state limit {self.max_states} exceeded while enumerating cuts"
                )
        return tuple(sorted(states))

    def _transitions(self, state: State, state_set: set[State]) -> list[Edge]:
        occupied = list(state) + [0]
        current = occupied[0]
        if current & ~self.full_layer:
            return []
        by_bit: list[list[int]] = [[] for _ in range(self.layer_size)]
        for index, pattern in enumerate(self.patterns):
            mask = pattern.masks[0]
            for bit in range(self.layer_size):
                if mask & (1 << bit):
                    by_bit[bit].append(index)

        found: dict[State, tuple[int, ...]] = {}
        chosen: list[int] = []

        def fill() -> None:
            missing = self.full_layer & ~occupied[0]
            if not missing:
                target = tuple(occupied[1:])
                if target in state_set:
                    found.setdefault(target, tuple(chosen))
                return
            bit = (missing & -missing).bit_length() - 1
            for pattern_index in by_bit[bit]:
                pattern = self.patterns[pattern_index]
                if any(
                    occupied[layer] & mask
                    for layer, mask in enumerate(pattern.masks)
                ):
                    continue
                for layer, mask in enumerate(pattern.masks):
                    occupied[layer] |= mask
                chosen.append(pattern_index)
                fill()
                chosen.pop()
                for layer, mask in enumerate(pattern.masks):
                    occupied[layer] ^= mask

        fill()
        return [Edge(state, target, found[target]) for target in sorted(found)]

    @staticmethod
    def _find_cycle(graph: dict[State, tuple[Edge, ...]]) -> tuple[Edge, ...] | None:
        """Return one directed cycle using an iterative three-color DFS."""
        color: dict[State, int] = {state: 0 for state in graph}
        for root in graph:
            if color[root]:
                continue
            color[root] = 1
            nodes = [root]
            incoming: list[Edge] = []
            active = {root: 0}
            stack = [(root, iter(graph[root]))]
            while stack:
                node, edges = stack[-1]
                try:
                    edge = next(edges)
                except StopIteration:
                    stack.pop()
                    color[node] = 2
                    active.pop(node)
                    nodes.pop()
                    if incoming:
                        incoming.pop()
                    continue
                target = edge.target
                if color[target] == 0:
                    color[target] = 1
                    active[target] = len(nodes)
                    nodes.append(target)
                    incoming.append(edge)
                    stack.append((target, iter(graph[target])))
                elif color[target] == 1:
                    start = active[target]
                    return tuple(incoming[start:] + [edge])
        return None

    @staticmethod
    def _graph_hash(graph: dict[State, tuple[Edge, ...]]) -> str:
        serial = [
            [
                list(state),
                [[list(edge.target), list(edge.patterns)] for edge in graph[state]],
            ]
            for state in sorted(graph)
        ]
        payload = json.dumps(serial, separators=(",", ":")).encode()
        return sha256(payload).hexdigest()

    def _build_graph(self) -> tuple[tuple[State, ...], dict[State, tuple[Edge, ...]], int]:
        """Build the complete finite graph or raise :class:`TransferLimit`."""
        states = self.enumerate_states()
        state_set = set(states)
        graph: dict[State, tuple[Edge, ...]] = {}
        edge_count = 0
        for state in states:
            outgoing = tuple(self._transitions(state, state_set))
            graph[state] = outgoing
            edge_count += len(outgoing)
            if edge_count > self.max_edges:
                raise TransferLimit(f"edge limit {self.max_edges} exceeded")
        return states, graph, edge_count

    @staticmethod
    def _topological_order(graph: dict[State, tuple[Edge, ...]]) -> tuple[State, ...]:
        """Return a complete topological order, or raise if the graph cycles."""
        indegree = {state: 0 for state in graph}
        for edges in graph.values():
            for edge in edges:
                indegree[edge.target] += 1
        ready = sorted(state for state, degree in indegree.items() if degree == 0)
        order = []
        while ready:
            state = ready.pop(0)
            order.append(state)
            for edge in graph[state]:
                indegree[edge.target] -= 1
                if indegree[edge.target] == 0:
                    ready.append(edge.target)
                    ready.sort()
        if len(order) != len(graph):
            raise ValueError("transfer graph contains a directed cycle")
        return tuple(order)

    def cycle_free_manifest(self) -> dict:
        """Emit a complete finite certificate for a cycle-free cylinder graph.

        The manifest contains geometry-derived placement patterns, every
        crossing contribution, every enumerated state and transition, and a
        topological order.  ``transfer_verify.py`` checks it through a separate
        implementation path.
        """
        states, graph, edge_count = self._build_graph()
        if self._find_cycle(graph) is not None:
            raise ValueError("cannot emit a cycle-free manifest for a cyclic graph")
        order = self._topological_order(graph)
        state_index = {state: index for index, state in enumerate(states)}
        return {
            "kind": "cylinder-cycle-free-certificate",
            "schema_version": 1,
            "shape": [list(cell) for cell in self.shape],
            "vector": list(self.vector),
            "basis": {
                "primitive": list(self.p),
                "multiplicity": self.g,
                "transverse": list(self.u),
            },
            "layer_size": self.layer_size,
            "interaction_span": self.span,
            "patterns": [
                {
                    "op": pattern.op,
                    "alpha": pattern.alpha,
                    "min_beta": pattern.min_beta,
                    "masks": list(pattern.masks),
                }
                for pattern in self.patterns
            ],
            "crossing_contributions": [
                list(contribution) for contribution in self._crossing_contributions()
            ],
            "states": [list(state) for state in states],
            "edges": [
                {
                    "source": state_index[state],
                    "target": state_index[edge.target],
                    "patterns": list(edge.patterns),
                }
                for state in states
                for edge in graph[state]
            ],
            "topological_order": [state_index[state] for state in order],
            "counts": {
                "patterns": len(self.patterns),
                "crossing_contributions": len(self._crossing_contributions()),
                "states": len(states),
                "edges": edge_count,
            },
            "graph_sha256": self._graph_hash(graph),
            "claim": (
                "The complete exact transfer graph for this shape/vector is "
                "acyclic; therefore no grid-aligned tiling has this period."
            ),
        }

    def _cycle_certificate(self, cycle: tuple[Edge, ...]) -> dict:
        length = len(cycle)
        second = (length * self.u[0], length * self.u[1])
        hnf = lattice_hnf(self.vector, second)
        placements = []
        for column, edge in enumerate(cycle):
            for pattern_index in edge.patterns:
                pattern = self.patterns[pattern_index]
                beta = column - pattern.min_beta
                tx = pattern.alpha * self.p[0] + beta * self.u[0]
                ty = pattern.alpha * self.p[1] + beta * self.u[1]
                placements.append([pattern.op, tx, ty])
        certificate = {
            "kind": "torus-exact-cover",
            "hnf": list(hnf),
            "index": hnf[0] * hnf[2],
            "tiles_per_domain": len(placements),
            "placements": placements,
        }
        if not verify_certificate(self.shape, certificate):
            raise AssertionError("transfer cycle failed independent A1 verification")
        return certificate

    def decide(self) -> TransferResult:
        try:
            states, graph, edges = self._build_graph()
        except TransferLimit as exc:
            return TransferResult(
                verdict="resource-exhausted",
                vector=self.vector,
                primitive=self.p,
                multiplicity=self.g,
                transverse=self.u,
                state_count=locals().get("states") and len(states) or 0,
                edge_count=locals().get("edges", 0),
                interaction_span=self.span,
                limit={
                    "max_states": self.max_states,
                    "max_edges": self.max_edges,
                    "message": str(exc),
                },
            )

        digest = self._graph_hash(graph)
        cycle = self._find_cycle(graph)
        if cycle is None:
            return TransferResult(
                verdict="cycle-free",
                vector=self.vector,
                primitive=self.p,
                multiplicity=self.g,
                transverse=self.u,
                state_count=len(states),
                edge_count=edges,
                interaction_span=self.span,
                graph_sha256=digest,
            )
        certificate = self._cycle_certificate(cycle)
        return TransferResult(
            verdict="cycle",
            vector=self.vector,
            primitive=self.p,
            multiplicity=self.g,
            transverse=self.u,
            state_count=len(states),
            edge_count=edges,
            interaction_span=self.span,
            graph_sha256=digest,
            cycle=cycle,
            certificate=certificate,
        )


def decide_period_vector(
    shape: Iterable[Cell],
    vector: Vector,
    *,
    max_states: int = 200_000,
    max_edges: int = 2_000_000,
) -> TransferResult:
    """Convenience entry point for the W1 reference engine."""
    return CylinderTransfer(
        shape,
        vector,
        max_states=max_states,
        max_edges=max_edges,
    ).decide()
