"""Kite substrate: the Laves [3.4.6.4] tiling (deltoidal trihexagonal).

This is the substrate the hat lives on (the hat is an 8-kite polykite).

Coordinate system ("hex coordinates"): an integer pair (x, y) represents the
plane point x*e1 + y*e2 with e1 = (1, 0), e2 = (1/2, sqrt(3)/2).  Every kite
vertex is an integer point in these coordinates, so ALL geometry here --
adjacency, symmetry, containment, boundary, area -- is exact integer
arithmetic.  No floating point.

Scale convention: hexagons have side 2, so the kite's short edge has length 1
and its long edge sqrt(3).  This matches the `hexPt` convention of Kaplan's
hatviz reference implementation, so published hat coordinates embed directly.

Squared Euclidean length of hex-coordinate vector (x, y) is x*x + x*y + y*y.

A kite cell is a triple (cx, cy, d): hexagon center (cx, cy) plus sector
d in 0..5.  The kite is the quadrilateral [C, M_{d-1}, V_d, M_d] where

  C     = hex center,
  V_k   = C + VDIR[k]  = hex vertex at polar angle 60*k degrees (distance 2),
  M_k   = C + MDIR[k]  = midpoint of the hex edge V_k -- V_{k+1}
                         (polar angle 30 + 60*k degrees, distance sqrt(3)).

Interior angles: 60 at C, 90 at the two midpoints, 120 at V_d.
Hexagon centers form the sublattice generated by (2, 2) and (-2, 4):
(x, y) is a center iff x and y are even and (y - x) % 6 == 0.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Points (hex coordinates)
# ---------------------------------------------------------------------------


def rot60(p: tuple[int, int]) -> tuple[int, int]:
    """Rotate a point 60 degrees counterclockwise about the origin."""
    x, y = p
    return (-y, x + y)


def mirror(p: tuple[int, int]) -> tuple[int, int]:
    """Reflect a point across the x-axis."""
    x, y = p
    return (x + y, -y)


def norm2(p: tuple[int, int]) -> int:
    """Squared Euclidean length of the vector p."""
    x, y = p
    return x * x + x * y + y * y


def cross(o: tuple[int, int], a: tuple[int, int], b: tuple[int, int]) -> int:
    """Cross product (a-o) x (b-o).  Sign matches the Euclidean plane
    (the hex->plane map has positive determinant)."""
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def _directions(first: tuple[int, int]) -> list[tuple[int, int]]:
    out = [first]
    for _ in range(5):
        out.append(rot60(out[-1]))
    return out


VDIR = _directions((2, 0))   # hex vertices, distance 2, angles 0,60,...,300
MDIR = _directions((1, 1))   # edge midpoints, distance sqrt(3), angles 30,90,...,330


def is_center(p: tuple[int, int]) -> bool:
    """Is p a hexagon center?"""
    x, y = p
    return x % 2 == 0 and y % 2 == 0 and (y - x) % 6 == 0


# ---------------------------------------------------------------------------
# Cells
# ---------------------------------------------------------------------------

Cell = tuple[int, int, int]  # (cx, cy, d)


def cell_vertices(cell: Cell) -> tuple[tuple[int, int], ...]:
    """The kite quad [C, M_{d-1}, V_d, M_d], counterclockwise."""
    cx, cy, d = cell
    m0 = MDIR[(d - 1) % 6]
    v = VDIR[d]
    m1 = MDIR[d]
    return (
        (cx, cy),
        (cx + m0[0], cy + m0[1]),
        (cx + v[0], cy + v[1]),
        (cx + m1[0], cy + m1[1]),
    )


def cell_edges(cell: Cell) -> list[frozenset[tuple[int, int]]]:
    """The kite's 4 edges as frozensets of endpoint pairs."""
    q = cell_vertices(cell)
    return [frozenset((q[i], q[(i + 1) % 4])) for i in range(4)]


def cell_centroid4(cell: Cell) -> tuple[int, int]:
    """4 times the kite centroid (an integer point)."""
    q = cell_vertices(cell)
    return (sum(p[0] for p in q), sum(p[1] for p in q))


def cell_neighbors(cell: Cell) -> list[Cell]:
    """The 4 edge-neighbors of a kite: 2 in the same hexagon (across the
    long edges), 2 in adjacent hexagons (across the short edges)."""
    cx, cy, d = cell
    ma = MDIR[(d - 1) % 6]
    mb = MDIR[d]
    return [
        (cx, cy, (d + 1) % 6),
        (cx, cy, (d - 1) % 6),
        (cx + 2 * ma[0], cy + 2 * ma[1], (d + 2) % 6),
        (cx + 2 * mb[0], cy + 2 * mb[1], (d + 4) % 6),
    ]


def cells_at_point(p: tuple[int, int]) -> list[Cell]:
    """All kite cells having p as a corner: 6 at a hex center, 3 at a hex
    vertex (one per surrounding hexagon), 4 at an edge midpoint (two per
    adjacent hexagon).  Angle check: 6*60 = 3*120 = 4*90 = 360."""
    if is_center(p):
        return [(p[0], p[1], d) for d in range(6)]
    out = []
    for k in range(6):
        c = (p[0] - VDIR[k][0], p[1] - VDIR[k][1])
        if is_center(c):
            out.append((c[0], c[1], k))
    if out:
        return out  # p is a hex vertex
    for k in range(6):
        c = (p[0] - MDIR[k][0], p[1] - MDIR[k][1])
        if is_center(c):
            # midpoint m_k is shared by kites k and k+1 of that hexagon
            out.append((c[0], c[1], k))
            out.append((c[0], c[1], (k + 1) % 6))
    return out  # p is an edge midpoint


# ---------------------------------------------------------------------------
# Symmetry group action (point group D6 about the origin, order 12)
# ---------------------------------------------------------------------------

N_OPS = 12  # ops 0..5: rot60^k; ops 6..11: mirror then rot60^k


def transform_point(p: tuple[int, int], op: int) -> tuple[int, int]:
    if op >= 6:
        p = mirror(p)
        op -= 6
    for _ in range(op):
        p = rot60(p)
    return p


def transform_cell(cell: Cell, op: int) -> Cell:
    cx, cy, d = cell
    if op >= 6:
        cx, cy = mirror((cx, cy))
        d = -d % 6
        op -= 6
    for _ in range(op):
        cx, cy = rot60((cx, cy))
    return (cx, cy, (d + op) % 6)


def translate_cell(cell: Cell, t: tuple[int, int]) -> Cell:
    return (cell[0] + t[0], cell[1] + t[1], cell[2])


def canonical_form(cells) -> tuple[Cell, ...]:
    """Canonical representative of a cell set under the full symmetry group
    of the kite grid (D6 point group x hex-center translations).

    Lex order on (cx, cy, d) is translation-invariant, so for each of the 12
    point-group images we translate the lex-min cell's center to the origin
    and take the sorted tuple; the canonical form is the min over images.
    """
    best = None
    for op in range(N_OPS):
        img = sorted(transform_cell(c, op) for c in cells)
        tx, ty = img[0][0], img[0][1]
        key = tuple((cx - tx, cy - ty, d) for cx, cy, d in img)
        if best is None or key < best:
            best = key
    return best


# ---------------------------------------------------------------------------
# Patch geometry: boundary and containment
# ---------------------------------------------------------------------------


def boundary_edges(cells) -> set[frozenset[tuple[int, int]]]:
    """Edges of the union of cells that belong to exactly one cell."""
    seen: dict[frozenset, int] = {}
    for c in cells:
        for e in cell_edges(c):
            seen[e] = seen.get(e, 0) + 1
    return {e for e, k in seen.items() if k == 1}


def boundary_cycle(cells) -> list[tuple[int, int]]:
    """Ordered vertex cycle of the union boundary.  Requires the union to be
    a topological disk whose boundary is a simple cycle (every boundary
    vertex has degree 2); raises ValueError otherwise."""
    adj: dict[tuple[int, int], list[tuple[int, int]]] = {}
    for e in boundary_edges(cells):
        a, b = tuple(e)
        adj.setdefault(a, []).append(b)
        adj.setdefault(b, []).append(a)
    for v, nbrs in adj.items():
        if len(nbrs) != 2:
            raise ValueError(f"boundary is not a simple cycle at vertex {v}")
    start = min(adj)
    cycle = [start, min(adj[start])]
    while True:
        prev, cur = cycle[-2], cycle[-1]
        nxt = adj[cur][0] if adj[cur][0] != prev else adj[cur][1]
        if nxt == start:
            break
        cycle.append(nxt)
    return cycle


def remove_collinear(poly: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Drop vertices where the polygon goes straight through."""
    n = len(poly)
    return [
        poly[i]
        for i in range(n)
        if cross(poly[(i - 1) % n], poly[i], poly[(i + 1) % n]) != 0
    ]


def shoelace2(poly: list[tuple[int, int]]) -> int:
    """Twice the signed area of the polygon in hex coordinates.
    True Euclidean area = shoelace2 * sqrt(3)/4.  One kite = 4."""
    s = 0
    n = len(poly)
    for i in range(n):
        x0, y0 = poly[i]
        x1, y1 = poly[(i + 1) % n]
        s += x0 * y1 - x1 * y0
    return s


def point_in_polygon(pt: tuple[int, int], poly: list[tuple[int, int]]) -> bool:
    """Strict interior test by winding number, exact integer arithmetic.
    Points on the boundary count as outside."""
    # y-coordinate in the plane is (sqrt(3)/2) * y_hex: the hex y alone
    # determines "above/below", so a standard crossing test on (x_plane
    # ordering via cross products, y = y_hex) is exact.
    wn = 0
    n = len(poly)
    px, py = pt
    for i in range(n):
        ax, ay = poly[i]
        bx, by = poly[(i + 1) % n]
        c = cross((ax, ay), (bx, by), (px, py))
        if c == 0 and min(ax, bx) <= px <= max(ax, bx) and min(ay, by) <= py <= max(ay, by):
            # On the segment's line and inside its bounding box: boundary.
            # (Collinear-off-segment points fall through harmlessly.)
            dot = (px - ax) * (bx - ax) + (py - ay) * (by - ay)
            len2 = (bx - ax) ** 2 + (by - ay) ** 2
            if 0 <= dot <= len2:
                return False
        if ay <= py < by and c > 0:
            wn += 1
        elif by <= py < ay and c < 0:
            wn -= 1
    return wn != 0


def cells_in_polygon(poly: list[tuple[int, int]]) -> list[Cell]:
    """All kite cells whose (open) interior lies inside the simple polygon
    `poly`, found by exact centroid-in-polygon tests over a bounding region.

    Because poly edges follow the grid, a kite is inside iff its centroid is.
    """
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    poly4 = [(4 * x, 4 * y) for x, y in poly]
    out = []
    # Hex centers have even coords with (y - x) % 6 == 0; scan a padded box.
    for cx in range(min(xs) - 4, max(xs) + 5):
        for cy in range(min(ys) - 4, max(ys) + 5):
            if not is_center((cx, cy)):
                continue
            for d in range(6):
                if point_in_polygon(cell_centroid4((cx, cy, d)), poly4):
                    out.append((cx, cy, d))
    return sorted(out)
