"""An ancestry-blind SFT generated by the 18 physical Spectre coronas.

The local rule says only that every complete edge corona belongs to the
observed 18-type language.  No parent variables occur in this layer.  Exact
next-ring SAT then provides the finite cases from which parent existence and
uniqueness may be derived rather than assumed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from einstein.geometry.cyclotomic import Pose, compose_pose, relative_pose
from einstein.tilings.spectre.patches import (
    _candidate_ring_tiles,
    patch_edge_incidence,
    poses_overlap,
)


@dataclass(frozen=True)
class LanguageExtension:
    solutions: tuple[tuple[Pose, ...], ...]
    physical_candidates: int
    local_options: int
    sat_calls: int
    solver: str


def completed_coronas(patch: Sequence[Pose]):
    """Return ``(center, rooted signature)`` for every complete tile."""
    patch = tuple(patch)
    index = {pose: i for i, pose in enumerate(patch)}
    incidence, _ = patch_edge_incidence(patch)
    adjacency = [set() for _ in patch]
    exposed = [0] * len(patch)
    for owners in incidence.values():
        if len(owners) == 1:
            exposed[index[owners[0]]] += 1
        elif len(owners) == 2:
            left, right = map(index.__getitem__, owners)
            adjacency[left].add(right)
            adjacency[right].add(left)
        else:
            raise ValueError("invalid physical edge incidence")
    return tuple(
        (
            pose,
            tuple(sorted(relative_pose(pose, patch[neighbor])
                         for neighbor in adjacency[i])),
        )
        for i, pose in enumerate(patch)
        if exposed[i] == 0
    )


def patch_obeys_language(patch: Sequence[Pose], allowed) -> bool:
    allowed = set(allowed)
    return all(signature in allowed for _, signature in completed_coronas(patch))


def _at_most_one(variables):
    return [
        [-left, -right]
        for position, left in enumerate(variables)
        for right in variables[position + 1:]
    ]


def extend_language_ring(
    patch: Sequence[Pose], allowed_coronas, solution_limit: int = 1_000_000,
) -> LanguageExtension:
    """Enumerate all exact next rings that keep every inner corona allowed."""
    if solution_limit < 1:
        raise ValueError("solution_limit must be positive")
    patch = tuple(sorted(set(patch)))
    patch_set = set(patch)
    allowed = tuple(allowed_coronas)
    exposed, candidate_cover = _candidate_ring_tiles(patch)
    candidates = tuple(sorted(candidate_cover))
    x_vars = tuple(range(1, len(candidates) + 1))
    candidate_index = {pose: i for i, pose in enumerate(candidates)}
    clauses: list[list[int]] = []

    by_edge = [[] for _ in exposed]
    for index, pose in enumerate(candidates):
        for edge in candidate_cover[pose]:
            by_edge[edge].append(x_vars[index])
    if not all(by_edge):
        return LanguageExtension((), len(candidates), 0, 0, "CaDiCaL 1.9.5")
    for covering in by_edge:
        clauses.append(covering)
        clauses.extend(_at_most_one(covering))
    for left, pose in enumerate(candidates):
        for right in range(left):
            if poses_overlap(pose, candidates[right]):
                clauses.append([-x_vars[left], -x_vars[right]])

    incidence, _ = patch_edge_incidence(patch)
    existing = {pose: set() for pose in patch}
    exposed_owner = {}
    for key, owners in incidence.items():
        if len(owners) == 1:
            exposed_owner[key] = owners[0]
        else:
            left, right = owners
            existing[left].add(right)
            existing[right].add(left)
    touching = {pose: set() for pose in patch}
    for candidate, edges in candidate_cover.items():
        for edge in edges:
            touching[exposed_owner[exposed[edge]]].add(candidate)

    next_variable = len(candidates) + 1
    option_count = 0
    for center in patch:
        options = []
        for corona in allowed:
            required = {compose_pose(center, relative) for relative in corona}
            if not existing[center] <= required:
                continue
            absent = required - patch_set
            if not absent <= touching[center]:
                continue
            if required & patch_set != existing[center]:
                continue
            selector = next_variable
            next_variable += 1
            options.append(selector)
            option_count += 1
            for candidate in touching[center]:
                variable = x_vars[candidate_index[candidate]]
                clauses.append([
                    -selector, variable if candidate in absent else -variable
                ])
        if not options:
            return LanguageExtension(
                (), len(candidates), option_count, 0, "CaDiCaL 1.9.5"
            )
        clauses.append(options)

    from pysat.solvers import Cadical195

    solutions = []
    calls = 0
    with Cadical195(bootstrap_with=clauses) as solver:
        while len(solutions) < solution_limit:
            calls += 1
            if not solver.solve():
                break
            positive = {literal for literal in solver.get_model() if literal > 0}
            ring = tuple(
                candidates[index]
                for index, variable in enumerate(x_vars)
                if variable in positive
            )
            solutions.append(tuple(sorted(ring)))
            ring_set = set(ring)
            solver.add_clause([
                -x_vars[index] if pose in ring_set else x_vars[index]
                for index, pose in enumerate(candidates)
            ])
    result = tuple(sorted(set(solutions)))
    return LanguageExtension(
        result, len(candidates), option_count, calls, "CaDiCaL 1.9.5"
    )


def verify_language_extension(patch, ring, allowed_coronas) -> bool:
    """Check a stored physical ring and every completed inner corona."""
    patch = tuple(sorted(set(patch)))
    exposed, candidate_cover = _candidate_ring_tiles(patch)
    ring = tuple(ring)
    if len(set(ring)) != len(ring) or not set(ring) <= set(candidate_cover):
        return False
    if any(poses_overlap(left, right)
           for position, left in enumerate(ring) for right in ring[:position]):
        return False
    if any(sum(edge in candidate_cover[pose] for pose in ring) != 1
           for edge in range(len(exposed))):
        return False
    final = (*patch, *ring)
    completed = dict(completed_coronas(final))
    return (
        all(center in completed for center in patch)
        and all(completed[center] in set(allowed_coronas) for center in patch)
    )
