"""Exact finite recurrence for the Spectre supertile geometry.

The vendored generator constructs each level from four distinguished module
points (a ``quad``).  Its construction uses only integer-linear operations on
those sixteen coordinates.  Consequently the apparently level-dependent
child translations are generated by one stationary 16-dimensional integer
recurrence.  This module exposes that recurrence without importing the
table-generating script (which has file-writing side effects).
"""

from __future__ import annotations

import ast
from collections import Counter
from fractions import Fraction
from hashlib import sha256

from einstein.geometry.cyclotomic import (
    Pose,
    Vec4,
    apply_sr,
    compose_pose,
    compare_quadratic,
    madd,
    mneg,
)


ZERO: Vec4 = (0, 0, 0, 0)
IDENTITY: Pose = (0, 0, ZERO)
MIRROR: Pose = (1, 0, ZERO)
UNIT_DIRECTIONS = tuple(apply_sr(0, k, (1, 0, 0, 0)) for k in range(12))
UNIT_DIRECTION_INDEX = {vector: index for index, vector in enumerate(UNIT_DIRECTIONS)}

EDGE_DIRECTIONS = (0, 10, 1, 3, 0, 2, 5, 7, 4, 6, 6, 8, 11, 9)
TRANSFORMATION_RULES = (
    (60, 3, 1),
    (0, 2, 0),
    (60, 3, 1),
    (60, 3, 1),
    (0, 2, 0),
    (60, 3, 1),
    (-120, 3, 3),
)


def _spectre_points() -> tuple[Vec4, ...]:
    directions = tuple(apply_sr(0, k, (1, 0, 0, 0)) for k in range(12))
    points = [ZERO]
    for direction in EDGE_DIRECTIONS[:-1]:
        points.append(madd(points[-1], directions[direction]))
    if madd(points[-1], directions[EDGE_DIRECTIONS[-1]]) != ZERO:
        raise AssertionError("Spectre boundary does not close")
    return tuple(points)


SPECTRE_POINTS = _spectre_points()
QUAD0 = tuple(SPECTRE_POINTS[index] for index in (3, 5, 7, 11))
GAMMA_SECOND: Pose = (0, 1, SPECTRE_POINTS[8])

LABELS = ("Gamma", "Delta", "Theta", "Lambda", "Xi", "Pi", "Sigma", "Phi", "Psi")
SUBSTITUTION_RULES = {
    "Gamma": ("Pi", "Delta", None, "Theta", "Sigma", "Xi", "Phi", "Gamma"),
    "Delta": ("Xi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Phi", "Gamma"),
    "Theta": ("Psi", "Delta", "Pi", "Phi", "Sigma", "Pi", "Phi", "Gamma"),
    "Lambda": ("Psi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Phi", "Gamma"),
    "Xi": ("Psi", "Delta", "Pi", "Phi", "Sigma", "Psi", "Phi", "Gamma"),
    "Pi": ("Psi", "Delta", "Xi", "Phi", "Sigma", "Psi", "Phi", "Gamma"),
    "Sigma": ("Xi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Lambda", "Gamma"),
    "Phi": ("Psi", "Delta", "Psi", "Phi", "Sigma", "Pi", "Phi", "Gamma"),
    "Psi": ("Psi", "Delta", "Psi", "Phi", "Sigma", "Psi", "Phi", "Gamma"),
}


def verify_binary_geometry_quotient():
    """Prove the nine labels collapse to full/missing geometric supports.

    Labels remain essential combinatorially.  Geometrically, however, every
    non-Gamma label has the same eight occupied slots (seven full children and
    one Gamma/missing child), while Gamma omits slot two.  Since all non-Gamma
    level-zero supports are one Spectre and Gamma is the two-Spectre mystic,
    induction leaves exactly two support geometries at every level.
    """
    kind = {label: ("missing" if label == "Gamma" else "full") for label in LABELS}
    patterns = {}
    for label, rule in SUBSTITUTION_RULES.items():
        patterns[label] = tuple(None if child is None else kind[child] for child in rule)
    full_pattern = (
        "full", "full", "full", "full", "full", "full", "full", "missing"
    )
    missing_pattern = (
        "full", "full", None, "full", "full", "full", "full", "missing"
    )
    if any(patterns[label] != full_pattern for label in LABELS if label != "Gamma"):
        raise ValueError("non-Gamma labels do not share one geometric rule")
    if patterns["Gamma"] != missing_pattern:
        raise ValueError("Gamma does not realize the missing geometric rule")
    return {
        "label_count": len(LABELS),
        "geometric_support_types": 2,
        "type_for_label": kind,
        "full_child_pattern": list(full_pattern),
        "missing_child_pattern": list(missing_pattern),
        "valid_at_all_levels_by_induction": True,
    }


def _apply(pose: Pose, point: Vec4) -> Vec4:
    s, r, translation = pose
    return madd(translation, apply_sr(s, r, point))


def _rotation(degrees: int) -> Pose:
    return 0, (degrees // 30) % 12, ZERO


def _translation(vector: Vec4) -> Pose:
    return 0, 0, vector


def build_level_transforms(
    quad: tuple[Vec4, Vec4, Vec4, Vec4],
) -> tuple[tuple[Pose, ...], tuple[Vec4, Vec4, Vec4, Vec4]]:
    """Return the eight child poses and next quad, exactly.

    This is a side-effect-free port of ``vendor/spectre/gen_tables.py``'s
    ``build_level_transforms``.  All eight children carry one reflection; the
    rotations are level-independent and only their translations evolve.
    """
    transformations = [IDENTITY]
    total_angle = 0
    rotation = IDENTITY
    transformed_quad = list(quad)
    for angle, source_index, target_index in TRANSFORMATION_RULES:
        if angle:
            total_angle += angle
            rotation = _rotation(total_angle)
            transformed_quad = [_apply(rotation, point) for point in quad]
        shift = madd(
            _apply(transformations[-1], quad[source_index]),
            mneg(transformed_quad[target_index]),
        )
        transformations.append(
            compose_pose(_translation(shift), rotation)
        )
    transformations = tuple(
        compose_pose(MIRROR, transform) for transform in transformations
    )
    next_quad = (
        _apply(transformations[6], quad[2]),
        _apply(transformations[5], quad[1]),
        _apply(transformations[3], quad[2]),
        _apply(transformations[0], quad[1]),
    )
    return transformations, next_quad


def flatten_quad(quad: tuple[Vec4, Vec4, Vec4, Vec4]) -> tuple[int, ...]:
    return tuple(coordinate for point in quad for coordinate in point)


def unflatten_quad(values) -> tuple[Vec4, Vec4, Vec4, Vec4]:
    values = tuple(values)
    if len(values) != 16:
        raise ValueError("a Spectre quad has exactly sixteen coordinates")
    if not all(isinstance(value, int) for value in values):
        raise ValueError("quad coordinates must be integers")
    return tuple(tuple(values[4 * i:4 * i + 4]) for i in range(4))  # type: ignore[return-value]


def recurrence_matrix() -> tuple[tuple[int, ...], ...]:
    """The stationary 16x16 integer matrix ``q[level+1] = F q[level]``."""
    columns = []
    for column in range(16):
        basis = [0] * 16
        basis[column] = 1
        _, next_quad = build_level_transforms(unflatten_quad(basis))
        columns.append(flatten_quad(next_quad))
    return tuple(
        tuple(columns[column][row] for column in range(16))
        for row in range(16)
    )


def matrix_vector(matrix, vector) -> tuple[int, ...]:
    vector = tuple(vector)
    if any(len(row) != len(vector) for row in matrix):
        raise ValueError("matrix and vector dimensions disagree")
    return tuple(sum(a * b for a, b in zip(row, vector)) for row in matrix)


def matrix_product(left, right) -> tuple[tuple[int, ...], ...]:
    if not left or not right or len(left[0]) != len(right):
        raise ValueError("matrix dimensions disagree")
    columns = tuple(zip(*right))
    return tuple(
        tuple(sum(a * b for a, b in zip(row, column)) for column in columns)
        for row in left
    )


def matrix_polynomial(matrix, coefficients) -> tuple[tuple[int, ...], ...]:
    """Evaluate a polynomial, whose coefficients are constant-first."""
    size = len(matrix)
    if not size or any(len(row) != size for row in matrix):
        raise ValueError("matrix must be nonempty and square")
    coefficients = tuple(coefficients)
    result = [[0] * size for _ in range(size)]
    power = tuple(tuple(int(i == j) for j in range(size)) for i in range(size))
    for coefficient in coefficients:
        for i in range(size):
            for j in range(size):
                result[i][j] += coefficient * power[i][j]
        power = matrix_product(power, matrix)
    return tuple(tuple(row) for row in result)


def integer_determinant(matrix) -> int:
    """Fraction-free Bareiss determinant for a square integer matrix."""
    size = len(matrix)
    if not size or any(len(row) != size for row in matrix):
        raise ValueError("matrix must be nonempty and square")
    work = [list(row) for row in matrix]
    sign = 1
    previous = 1
    for pivot_index in range(size - 1):
        if work[pivot_index][pivot_index] == 0:
            swap = next(
                (row for row in range(pivot_index + 1, size)
                 if work[row][pivot_index] != 0),
                None,
            )
            if swap is None:
                return 0
            work[pivot_index], work[swap] = work[swap], work[pivot_index]
            sign *= -1
        pivot = work[pivot_index][pivot_index]
        for i in range(pivot_index + 1, size):
            for j in range(pivot_index + 1, size):
                numerator = work[i][j] * pivot - work[i][pivot_index] * work[pivot_index][j]
                if numerator % previous:
                    raise ArithmeticError("Bareiss division was not exact")
                work[i][j] = numerator // previous
        previous = pivot
    return sign * work[-1][-1]


# (x^2 - 1)^2 (x^4 - 8*x^2 + 1).  This is the exact minimal polynomial:
# the unit eigenvalues have nontrivial size-two Jordan blocks, while the four
# irrational roots are simple in the minimal polynomial.
ANNIHILATING_POLYNOMIAL = (1, 0, -10, 0, 18, 0, -10, 0, 1)


def parse_rust_child_translations(source: str):
    """Extract ``CHILD_T`` from the generated Rust table as integer tuples."""
    marker = "pub const CHILD_T"
    location = source.find(marker)
    if location < 0:
        raise ValueError("Rust source has no CHILD_T table")
    start = source.find("=", location)
    end = source.find(";", start)
    if start < 0 or end < 0:
        raise ValueError("malformed Rust CHILD_T declaration")
    value = ast.literal_eval(source[start + 1:end].strip())
    try:
        parsed = tuple(
            tuple(tuple(int(coordinate) for coordinate in vector) for vector in level)
            for level in value
        )
    except (TypeError, ValueError) as exc:
        raise ValueError("CHILD_T is not a rectangular integer table") from exc
    if not parsed or any(
        len(level) != 8 or any(len(vector) != 4 for vector in level)
        for level in parsed
    ):
        raise ValueError("CHILD_T must have eight rank-four vectors per level")
    return parsed


def level_geometry(levels: int):
    """Generate exact quads and child poses for levels 1 through ``levels``."""
    if levels < 0:
        raise ValueError("levels must be nonnegative")
    quad = QUAD0
    output = []
    for level in range(1, levels + 1):
        children, next_quad = build_level_transforms(quad)
        output.append({
            "level": level,
            "quad": quad,
            "children": children,
            "next_quad": next_quad,
        })
        quad = next_quad
    return tuple(output)


def verify_stationary_recurrence(levels: int = 32):
    """Cold exact checks for recurrence and level-independent child frames."""
    matrix = recurrence_matrix()
    determinant = integer_determinant(matrix)
    if determinant not in (-1, 1):
        raise ValueError("geometry recurrence is not unimodular")
    annihilator = matrix_polynomial(matrix, ANNIHILATING_POLYNOMIAL)
    if any(any(value for value in row) for row in annihilator):
        raise ValueError("claimed polynomial does not annihilate recurrence")
    geometry = level_geometry(levels)
    expected_frames = None
    for row in geometry:
        predicted = matrix_vector(matrix, flatten_quad(row["quad"]))
        if predicted != flatten_quad(row["next_quad"]):
            raise ValueError(f"recurrence fails at level {row['level']}")
        frames = tuple((pose[0], pose[1]) for pose in row["children"])
        if expected_frames is None:
            expected_frames = frames
        elif frames != expected_frames:
            raise ValueError("child reflection/rotation frames vary by level")
    return {
        "dimension": 16,
        "levels_verified": levels,
        "matrix": [list(row) for row in matrix],
        "determinant": determinant,
        "annihilating_polynomial_constant_first": list(ANNIHILATING_POLYNOMIAL),
        "expanding_linear_factor": "sqrt(4+sqrt(15))",
        "expanding_two_level_factor": "4+sqrt(15)",
        "initial_quad": [list(point) for point in QUAD0],
        "child_frames": [list(frame) for frame in (expected_frames or ())],
        "final_quad": (
            [list(point) for point in geometry[-1]["next_quad"]]
            if geometry else [list(point) for point in QUAD0]
        ),
    }


def compare_vendored_translations(source: str):
    """Compare every materialized Rust child translation with the recurrence."""
    vendored = parse_rust_child_translations(source)
    generated = tuple(
        tuple(pose[2] for pose in row["children"])
        for row in level_geometry(len(vendored))
    )
    if generated != vendored:
        for index, (actual, expected) in enumerate(zip(generated, vendored), 1):
            if actual != expected:
                raise ValueError(f"vendored CHILD_T mismatch at level {index}")
        raise ValueError("vendored CHILD_T has an unexpected number of levels")
    return {
        "levels": len(vendored),
        "children_per_level": 8,
        "vectors_compared": 8 * len(vendored),
        "all_equal": True,
    }


def exact_leaves(level: int, top_label: str):
    """Expand a vendored Spectre supertile to exact physical-tile poses."""
    if top_label not in SUBSTITUTION_RULES:
        raise ValueError(f"unknown Spectre label {top_label}")
    if level < 0:
        raise ValueError("level must be nonnegative")
    geometry = level_geometry(level)
    leaves = []

    def recurse(depth: int, label: str, pose: Pose):
        if depth == 0:
            if label == "Gamma":
                leaves.append(("Gamma1", pose))
                leaves.append(("Gamma2", compose_pose(pose, GAMMA_SECOND)))
            else:
                leaves.append((label, pose))
            return
        children = geometry[depth - 1]["children"]
        for index, child_label in enumerate(SUBSTITUTION_RULES[label]):
            if child_label is not None:
                recurse(
                    depth - 1,
                    child_label,
                    compose_pose(pose, children[index]),
                )

    recurse(level, top_label, IDENTITY)
    return tuple(leaves)


def _coordinate_pairs(point: Vec4):
    """Return twice the Cartesian x/y coordinates as Q(sqrt(3)) pairs."""
    u0, u1, u2, u3 = point
    return (2 * u0 + u2, u1), (2 * u3 + u1, u2)


def _pair_subtract(left, right):
    return left[0] - right[0], left[1] - right[1]


def _pair_multiply(left, right):
    return (
        left[0] * right[0] + 3 * left[1] * right[1],
        left[0] * right[1] + left[1] * right[0],
    )


def _orientation(a: Vec4, b: Vec4, c: Vec4) -> int:
    ax, ay = _coordinate_pairs(a)
    bx, by = _coordinate_pairs(b)
    cx, cy = _coordinate_pairs(c)
    abx, aby = _pair_subtract(bx, ax), _pair_subtract(by, ay)
    acx, acy = _pair_subtract(cx, ax), _pair_subtract(cy, ay)
    cross = _pair_subtract(_pair_multiply(abx, acy), _pair_multiply(aby, acx))
    return compare_quadratic(cross, (0, 0))


def _coordinate_compare(left: Vec4, right: Vec4, axis: int) -> int:
    return compare_quadratic(
        _coordinate_pairs(left)[axis], _coordinate_pairs(right)[axis]
    )


def _between(value: Vec4, end1: Vec4, end2: Vec4, axis: int) -> bool:
    comparison = _coordinate_compare(end1, end2, axis)
    low, high = (end1, end2) if comparison <= 0 else (end2, end1)
    return (
        _coordinate_compare(low, value, axis) <= 0
        and _coordinate_compare(value, high, axis) <= 0
    )


def _on_segment(point: Vec4, start: Vec4, end: Vec4) -> bool:
    return (
        _orientation(start, end, point) == 0
        and _between(point, start, end, 0)
        and _between(point, start, end, 1)
    )


def _proper_crossing(a: Vec4, b: Vec4, c: Vec4, d: Vec4) -> bool:
    ab_c, ab_d = _orientation(a, b, c), _orientation(a, b, d)
    cd_a, cd_b = _orientation(c, d, a), _orientation(c, d, b)
    return ab_c * ab_d < 0 and cd_a * cd_b < 0


def _segments_intersect(a: Vec4, b: Vec4, c: Vec4, d: Vec4) -> bool:
    if _proper_crossing(a, b, c, d):
        return True
    return (
        _on_segment(a, c, d)
        or _on_segment(b, c, d)
        or _on_segment(c, a, b)
        or _on_segment(d, a, b)
    )


def _point_location(point: Vec4, polygon) -> int:
    """Return -1 outside, 0 on boundary, +1 strictly inside exactly."""
    winding = 0
    for start, end in zip(polygon, polygon[1:] + polygon[:1]):
        if _on_segment(point, start, end):
            return 0
        sy = _coordinate_compare(start, point, 1)
        ey = _coordinate_compare(end, point, 1)
        side = _orientation(start, end, point)
        if sy <= 0 < ey and side > 0:
            winding += 1
        elif ey <= 0 < sy and side < 0:
            winding -= 1
    return 1 if winding else -1


def _transformed_polygon(pose: Pose):
    return tuple(_apply(pose, point) for point in SPECTRE_POINTS)


def _polygons_overlap_interior(left, right) -> bool:
    if set(left) == set(right):
        return True
    for a, b in zip(left, left[1:] + left[:1]):
        for c, d in zip(right, right[1:] + right[:1]):
            if _proper_crossing(a, b, c, d):
                return True
    return (
        any(_point_location(point, right) > 0 for point in left)
        or any(_point_location(point, left) > 0 for point in right)
    )


def verify_leaf_patch(leaves):
    """Exact physical-polygon nonoverlap and edge-connectivity certificate."""
    leaves = tuple(leaves)
    polygons = tuple(_transformed_polygon(pose) for _, pose in leaves)
    overlap_pairs = []
    adjacency = [set() for _ in leaves]
    edge_sets = []
    for polygon in polygons:
        edge_sets.append({
            frozenset((start, end))
            for start, end in zip(polygon, polygon[1:] + polygon[:1])
        })
    for i in range(len(leaves)):
        for j in range(i + 1, len(leaves)):
            if _polygons_overlap_interior(polygons[i], polygons[j]):
                overlap_pairs.append((i, j))
            if edge_sets[i] & edge_sets[j]:
                adjacency[i].add(j)
                adjacency[j].add(i)
    connected = not leaves
    if leaves:
        reached = {0}
        frontier = [0]
        while frontier:
            node = frontier.pop()
            for neighbor in adjacency[node] - reached:
                reached.add(neighbor)
                frontier.append(neighbor)
        connected = len(reached) == len(leaves)
    edge_incidence = Counter(edge for edges in edge_sets for edge in edges)
    manifold_edges = max(edge_incidence.values(), default=0) <= 2
    boundary_edges = sum(count == 1 for count in edge_incidence.values())
    return {
        "tiles": len(leaves),
        "interior_overlap_pairs": [list(pair) for pair in overlap_pairs],
        "interiors_disjoint": not overlap_pairs,
        "edge_connected": connected,
        "edge_incidence_at_most_two": manifold_edges,
        "boundary_unit_edges": boundary_edges,
        "legal_patch": not overlap_pairs and connected and manifold_edges,
    }


def realized_patch_evidence(max_complete_level: int = 1):
    """Cold exact legality checks for finite prefixes of all nine labels."""
    if max_complete_level < 0:
        raise ValueError("max_complete_level must be nonnegative")
    checks = []
    for level in range(max_complete_level + 1):
        for label in LABELS:
            report = verify_leaf_patch(exact_leaves(level, label))
            if not report["legal_patch"]:
                raise ValueError(f"illegal realized patch at level {level} {label}")
            checks.append({"level": level, "label": label, **report})
    return {
        "complete_levels": max_complete_level,
        "labels_per_level": len(LABELS),
        "patches_checked": len(checks),
        "all_legal": True,
        "checks": checks,
        "inductive_all_levels": False,
    }


def abstract_boundary_report(leaves):
    """Exact edge-complex topology of a realized leaf family.

    This does not by itself rule out transverse crossings between nonincident
    edges, so it is intentionally called an *abstract* boundary report rather
    than a legality proof.
    """
    leaves = tuple(leaves)
    polygons = tuple(_transformed_polygon(pose) for _, pose in leaves)
    edge_incidence = Counter()
    vertices = set()
    for polygon in polygons:
        vertices.update(polygon)
        for start, end in zip(polygon, polygon[1:] + polygon[:1]):
            edge_incidence[frozenset((start, end))] += 1
    boundary_edges = {
        edge for edge, count in edge_incidence.items() if count == 1
    }
    adjacency = {}
    for edge in boundary_edges:
        start, end = sorted(edge)
        adjacency.setdefault(start, set()).add(end)
        adjacency.setdefault(end, set()).add(start)
    degree_counts = Counter(len(neighbors) for neighbors in adjacency.values())
    unused = set(boundary_edges)
    cycles = []
    while unused:
        seed = min(tuple(sorted(edge)) for edge in unused)
        start, current = seed
        previous = start
        directions = []
        while True:
            edge = frozenset((previous, current))
            if edge not in unused:
                raise ValueError("boundary traversal repeated an edge")
            unused.remove(edge)
            vector = madd(current, mneg(previous))
            if vector not in UNIT_DIRECTION_INDEX:
                raise ValueError("boundary contains a non-unit edge")
            directions.append(UNIT_DIRECTION_INDEX[vector])
            candidates = adjacency[current] - {previous}
            if current == start:
                break
            if len(candidates) != 1:
                raise ValueError("boundary is not a disjoint union of cycles")
            previous, current = current, next(iter(candidates))
            if current == start:
                closing = frozenset((previous, current))
                if closing not in unused:
                    raise ValueError("boundary cycle does not close")
                unused.remove(closing)
                vector = madd(current, mneg(previous))
                directions.append(UNIT_DIRECTION_INDEX[vector])
                break
        counts = [0] * 12
        for direction in directions:
            counts[direction] += 1
        cycles.append({"length": len(directions), "direction_counts": counts})
    cycles.sort(key=lambda cycle: (cycle["length"], cycle["direction_counts"]))
    euler = len(vertices) - len(edge_incidence) + len(leaves)
    return {
        "tiles": len(leaves),
        "vertices": len(vertices),
        "edges": len(edge_incidence),
        "euler_characteristic": euler,
        "maximum_edge_incidence": max(edge_incidence.values(), default=0),
        "boundary_vertex_degree_counts": [
            [degree, degree_counts[degree]] for degree in sorted(degree_counts)
        ],
        "boundary_components": len(cycles),
        "boundary_cycles": cycles,
        "abstract_disk": (
            euler == 1
            and max(edge_incidence.values(), default=0) <= 2
            and len(cycles) == 1
            and degree_counts == {2: len(adjacency)}
        ),
    }


def binary_boundary_prefix(max_level: int = 3):
    """Check the two all-level geometry classes on a finite exact prefix."""
    if max_level < 0:
        raise ValueError("max_level must be nonnegative")
    rows = []
    for level in range(max_level + 1):
        full_leaves = exact_leaves(level, "Delta")
        missing_leaves = exact_leaves(level, "Gamma")
        full_poses = {pose for _, pose in full_leaves}
        for label in LABELS:
            if label == "Gamma":
                continue
            if {pose for _, pose in exact_leaves(level, label)} != full_poses:
                raise ValueError(f"full support mismatch at level {level} {label}")
        for kind, leaves in (("full", full_leaves), ("missing", missing_leaves)):
            report = abstract_boundary_report(leaves)
            if not report["abstract_disk"]:
                raise ValueError(f"non-disk abstract support at level {level} {kind}")
            rows.append({"level": level, "kind": kind, **report})
    return {
        "maximum_level": max_level,
        "support_types": 2,
        "reports": rows,
        "all_abstract_disks": True,
        "proves_planar_nonintersection": False,
    }


def _boundary_adjacency(leaves):
    incidence = Counter()
    for _, pose in leaves:
        polygon = _transformed_polygon(pose)
        for start, end in zip(polygon, polygon[1:] + polygon[:1]):
            incidence[frozenset((start, end))] += 1
    adjacency = {}
    for edge, count in incidence.items():
        if count == 1:
            start, end = tuple(edge)
            adjacency.setdefault(start, set()).add(end)
            adjacency.setdefault(end, set()).add(start)
    if any(len(neighbors) != 2 for neighbors in adjacency.values()):
        raise ValueError("boundary is not a union of cycles")
    return adjacency


def _cycle_paths(adjacency, start, end):
    paths = []
    for first in sorted(adjacency[start]):
        path = [start]
        previous, current = start, first
        while current != end:
            path.append(current)
            candidates = adjacency[current] - {previous}
            if len(candidates) != 1:
                raise ValueError("boundary path branches")
            previous, current = current, next(iter(candidates))
        path.append(end)
        paths.append(tuple(path))
    if len(paths) != 2:
        raise ValueError("expected two paths on one boundary cycle")
    return tuple(paths)


def boundary_side_word(level: int):
    """Unit-direction word on the short full-boundary path q[2] -> q[1]."""
    if level < 0:
        raise ValueError("level must be nonnegative")
    quad = QUAD0 if level == 0 else level_geometry(level)[-1]["next_quad"]
    adjacency = _boundary_adjacency(exact_leaves(level, "Delta"))
    path = min(_cycle_paths(adjacency, quad[2], quad[1]), key=len)
    return tuple(
        UNIT_DIRECTION_INDEX[madd(end, mneg(start))]
        for start, end in zip(path, path[1:])
    )


def _quad_at_level(level: int):
    return QUAD0 if level == 0 else level_geometry(level)[-1]["next_quad"]


def actual_macro_side_words(level: int, kind: str):
    """Extract the four directed q-to-q boundary words from physical leaves."""
    if kind not in ("full", "missing"):
        raise ValueError("kind must be full or missing")
    label = "Delta" if kind == "full" else "Gamma"
    quad = _quad_at_level(level)
    adjacency = _boundary_adjacency(exact_leaves(level, label))
    words = {}
    for side, (start_index, end_index) in MACRO_SIDE_ENDPOINTS.items():
        if quad[start_index] not in adjacency or quad[end_index] not in adjacency:
            # The level-zero missing/Gamma support does not contain q[2].
            # Only its C side feeds the graph-directed recursion.
            continue
        other = {
            quad[index] for index in range(4)
            if index not in (start_index, end_index)
        }
        candidates = [
            path for path in _cycle_paths(
                adjacency, quad[start_index], quad[end_index]
            )
            if not any(vertex in other for vertex in path[1:-1])
        ]
        if len(candidates) != 1:
            raise ValueError(f"cannot isolate macro side {kind}/{side}")
        path = candidates[0]
        words[side] = tuple(
            UNIT_DIRECTION_INDEX[madd(end, mneg(start))]
            for start, end in zip(path, path[1:])
        )
    return words


def transform_direction_word(word, reverse: int, mirror: int, rotation: int):
    """Apply path reversal, then a module dihedral frame to a direction word."""
    word = tuple(word)
    if reverse:
        word = tuple((direction + 6) % 12 for direction in reversed(word))
    return tuple(
        (rotation + (direction if not mirror else 6 - direction)) % 12
        for direction in word
    )


def _word_between(side_words, start_index: int, end_index: int):
    for side, (start, end) in MACRO_SIDE_ENDPOINTS.items():
        if (start_index, end_index) == (start, end):
            return side_words[side]
        if (start_index, end_index) == (end, start):
            return transform_direction_word(side_words[side], 1, 0, 0)
    raise ValueError(f"quad endpoints {start_index}->{end_index} are not adjacent")


def recurrent_macro_side_words(max_level: int):
    """Generate the graph-directed full/missing boundary-word system."""
    if max_level < 0:
        raise ValueError("max_level must be nonnegative")
    levels = [{
        "full": actual_macro_side_words(0, "full"),
        "missing": actual_macro_side_words(0, "missing"),
    }]
    frames = tuple((pose[0], pose[1]) for pose in build_level_transforms(QUAD0)[0])
    for _level in range(1, max_level + 1):
        previous = levels[-1]
        current = {}
        for parent_kind, grammar in (
            ("full", FULL_MACRO_SIDE_CHAINS),
            ("missing", MISSING_MACRO_SIDE_CHAINS),
        ):
            current[parent_kind] = {}
            for side, chain in grammar.items():
                word = []
                for slot, start_index, end_index in chain:
                    # Slot seven is the Gamma/missing child.  Slot two in the
                    # missing-D grammar is virtual and contributes the full
                    # child's complementary C arc.
                    child_kind = "missing" if slot == 7 else "full"
                    local = _word_between(
                        previous[child_kind], start_index, end_index
                    )
                    mirror, rotation = frames[slot]
                    word.extend(transform_direction_word(
                        local, 0, mirror, rotation
                    ))
                current[parent_kind][side] = tuple(word)
        levels.append(current)
    return tuple(levels)


def macro_word_recurrence_evidence(max_level: int = 5):
    """Compare the graph-directed recursion with exact leaf boundaries."""
    predicted = recurrent_macro_side_words(max_level)
    rows = []
    for level, expected_level in enumerate(predicted):
        for kind in ("full", "missing"):
            actual = actual_macro_side_words(level, kind)
            for side in expected_level[kind]:
                if side not in actual:
                    raise ValueError(
                        f"missing actual macro side at {level} {kind}/{side}"
                    )
                expected = expected_level[kind][side]
                if actual[side] != expected:
                    raise ValueError(
                        f"macro word recurrence fails at {level} {kind}/{side}"
                    )
                rows.append({
                    "level": level,
                    "kind": kind,
                    "side": side,
                    "length": len(expected),
                    "sha256": sha256(bytes(expected)).hexdigest(),
                })
    return {
        "maximum_level": max_level,
        "side_types": 8,
        "checks": rows,
        "all_equal": True,
        "derived_from_macro_chain_grammar": True,
        "all_level_endpoint_identity": True,
        "all_level_simplicity_or_nonintersection": False,
    }


SQRT3_LOWER = Fraction(265, 153)
SQRT3_UPPER = Fraction(1351, 780)


def _coordinate_interval(point: Vec4, axis: int):
    constant, radical = _coordinate_pairs(point)[axis]
    if radical >= 0:
        low = Fraction(constant) + radical * SQRT3_LOWER
        high = Fraction(constant) + radical * SQRT3_UPPER
    else:
        low = Fraction(constant) + radical * SQRT3_UPPER
        high = Fraction(constant) + radical * SQRT3_LOWER
    return low / 2, high / 2


def recurrent_boundary_vertices(level: int, kind: str):
    """Closed boundary vertex cycle generated by the macro word recursion."""
    if level < 1 and kind == "missing":
        # q[2] is not on the level-zero Gamma boundary.
        leaves = (("Gamma1", IDENTITY), ("Gamma2", GAMMA_SECOND))
        adjacency = _boundary_adjacency(leaves)
        start = min(adjacency)
        previous, current = start, min(adjacency[start])
        path = [start]
        while current != start:
            path.append(current)
            candidates = adjacency[current] - {previous}
            if len(candidates) != 1:
                raise ValueError("level-zero missing boundary branches")
            previous, current = current, next(iter(candidates))
        path.append(start)
        return tuple(path)
    words = recurrent_macro_side_words(level)[level][kind]
    quad = _quad_at_level(level)
    current = quad[2]
    vertices = [current]
    for side in ("A", "B", "C", "D"):
        for direction in words[side]:
            current = madd(current, UNIT_DIRECTIONS[direction])
            vertices.append(current)
    if current != quad[2]:
        raise ValueError("recurrent macro boundary does not close")
    return tuple(vertices)


def exact_boundary_simplicity_report(level: int, kind: str):
    """Exact vertex and segment simplicity with rational-safe spatial bins."""
    vertices = recurrent_boundary_vertices(level, kind)
    edge_count = len(vertices) - 1
    repeated_vertices = len(vertices[:-1]) - len(set(vertices[:-1]))
    buckets = {}
    intersections = []
    interval_cache = {}

    def intervals(point):
        if point not in interval_cache:
            interval_cache[point] = (
                _coordinate_interval(point, 0),
                _coordinate_interval(point, 1),
            )
        return interval_cache[point]

    for index, (start, end) in enumerate(zip(vertices, vertices[1:])):
        start_box, end_box = intervals(start), intervals(end)
        x_low = min(start_box[0][0], end_box[0][0])
        x_high = max(start_box[0][1], end_box[0][1])
        y_low = min(start_box[1][0], end_box[1][0])
        y_high = max(start_box[1][1], end_box[1][1])
        cells = tuple(
            (x, y)
            for x in range(x_low.numerator // x_low.denominator,
                           x_high.numerator // x_high.denominator + 1)
            for y in range(y_low.numerator // y_low.denominator,
                           y_high.numerator // y_high.denominator + 1)
        )
        candidates = set()
        for cell in cells:
            candidates.update(buckets.get(cell, ()))
        for other in candidates:
            if index - other == 1 or (other == 0 and index == edge_count - 1):
                continue
            if _segments_intersect(
                vertices[other], vertices[other + 1], start, end
            ):
                intersections.append((other, index))
                if len(intersections) >= 20:
                    break
        for cell in cells:
            buckets.setdefault(cell, []).append(index)
        if len(intersections) >= 20:
            break
    return {
        "level": level,
        "kind": kind,
        "edges": edge_count,
        "repeated_nonclosing_vertices": repeated_vertices,
        "nonadjacent_segment_intersections": [list(pair) for pair in intersections],
        "simple": repeated_vertices == 0 and not intersections,
        "candidate_acceleration": (
            "rational sqrt(3) interval bins; every candidate is decided exactly"
        ),
    }


def boundary_simplicity_prefix(max_level: int = 6):
    if max_level < 1:
        raise ValueError("simplicity prefix starts at level one")
    reports = []
    for level in range(1, max_level + 1):
        for kind in ("full", "missing"):
            report = exact_boundary_simplicity_report(level, kind)
            if not report["simple"]:
                raise ValueError(f"nonsimple boundary at {level} {kind}")
            reports.append(report)
    return {
        "maximum_level": max_level,
        "reports": reports,
        "all_simple": True,
        "all_level_induction": False,
    }


def _dot_direction_pair(point: Vec4, direction: int):
    px, py = _coordinate_pairs(point)
    dx, dy = _coordinate_pairs(UNIT_DIRECTIONS[direction])
    x_term = _pair_multiply(px, dx)
    y_term = _pair_multiply(py, dy)
    # Four times the Euclidean dot product.  The positive scale is irrelevant
    # to comparisons and preserves integer Q(sqrt(3)) pairs.
    return x_term[0] + y_term[0], x_term[1] + y_term[1]


def _extreme_on_vertices(vertices, direction: int, maximum: bool):
    values = [_dot_direction_pair(point, direction) for point in vertices]
    best = values[0]
    indices = [0]
    for index, value in enumerate(values[1:], 1):
        comparison = compare_quadratic(value, best)
        if (comparison > 0 if maximum else comparison < 0):
            best = value
            indices = [index]
        elif comparison == 0:
            indices.append(index)
    return best, tuple(indices)


def _macro_piece_vertices(level: int, parent_kind: str):
    if level < 1:
        raise ValueError("macro pieces start at level one")
    previous = recurrent_macro_side_words(level - 1)[-1]
    geometry = level_geometry(level)[-1]
    quad = geometry["quad"]
    children = geometry["children"]
    grammar = (
        FULL_MACRO_SIDE_CHAINS if parent_kind == "full"
        else MISSING_MACRO_SIDE_CHAINS
    )
    pieces = []
    for side in ("A", "B", "C", "D"):
        for local_index, (slot, start_index, end_index) in enumerate(grammar[side]):
            child_kind = "missing" if slot == 7 else "full"
            local_word = _word_between(
                previous[child_kind], start_index, end_index
            )
            mirror, rotation, _translation_vector = children[slot]
            word = transform_direction_word(
                local_word, 0, mirror, rotation
            )
            point = _apply(children[slot], quad[start_index])
            vertices = [point]
            for direction in word:
                point = madd(point, UNIT_DIRECTIONS[direction])
                vertices.append(point)
            pieces.append({
                "side": side,
                "local_index": local_index,
                "slot": slot,
                "start_quad": start_index,
                "end_quad": end_index,
                "vertices": tuple(vertices),
            })
    return tuple(pieces)


def support_policy_prefix(max_level: int = 7, stable_from: int = 3):
    """Finite max-plus policy and nonadjacent separator stabilization gate."""
    if max_level < stable_from or stable_from < 1:
        raise ValueError("invalid support-policy prefix")
    winner_history = {}
    separator_history = {"full": {}, "missing": {}}
    pair_counts = {}
    for level in range(1, max_level + 1):
        for kind in ("full", "missing"):
            pieces = _macro_piece_vertices(level, kind)
            by_side = {
                side: [piece for piece in pieces if piece["side"] == side]
                for side in MACRO_SIDE_ENDPOINTS
            }
            for side, side_pieces in by_side.items():
                for direction in range(12):
                    for maximum in (False, True):
                        candidates = [
                            _extreme_on_vertices(
                                piece["vertices"], direction, maximum
                            )[0]
                            for piece in side_pieces
                        ]
                        best = candidates[0]
                        for value in candidates[1:]:
                            comparison = compare_quadratic(value, best)
                            if (comparison > 0 if maximum else comparison < 0):
                                best = value
                        winners = tuple(
                            index for index, value in enumerate(candidates)
                            if compare_quadratic(value, best) == 0
                        )
                        key = f"{kind}:{side}:{direction}:" + (
                            "max" if maximum else "min"
                        )
                        winner_history.setdefault(key, []).append(list(winners))

            nonadjacent = []
            count = len(pieces)
            for left in range(count):
                for right in range(left + 1, count):
                    if right == left + 1 or (left == 0 and right == count - 1):
                        continue
                    separators = []
                    for direction in range(12):
                        left_max = _extreme_on_vertices(
                            pieces[left]["vertices"], direction, True
                        )[0]
                        right_min = _extreme_on_vertices(
                            pieces[right]["vertices"], direction, False
                        )[0]
                        if compare_quadratic(left_max, right_min) < 0:
                            separators.append(direction)
                    key = f"{left}:{right}"
                    if level == 1:
                        separator_history[kind][key] = separators
                    else:
                        separator_history[kind][key] = sorted(
                            set(separator_history[kind][key]) & set(separators)
                        )
                    nonadjacent.append(key)
            pair_counts[kind] = len(nonadjacent)

    stable_index = stable_from - 1
    unstable_winners = {
        key: values for key, values in winner_history.items()
        if len({tuple(value) for value in values[stable_index:]}) != 1
    }
    missing_separators = {
        kind: [key for key, values in rows.items() if not values]
        for kind, rows in separator_history.items()
    }
    if unstable_winners:
        raise ValueError("support-extremum winner policy has not stabilized")
    if any(missing_separators.values()):
        raise ValueError("some nonadjacent macro pieces lack a stable separator")
    return {
        "maximum_level": max_level,
        "stable_from_level": stable_from,
        "support_states": len(winner_history),
        "winner_history": winner_history,
        "nonadjacent_pair_counts": pair_counts,
        "stable_separator_directions": separator_history,
        "all_winners_stable": True,
        "all_nonadjacent_pairs_stably_separated": True,
        "adjacent_interface_states_discharged": False,
        "all_level_proof": False,
    }


BOUNDARY_SIDE_RECIPE = (
    (1, 0, 1, 0),
    (1, 1, 1, 4),
    (2, 0, 0, 8),
    (1, 1, 1, 6),
    (1, 0, 1, 2),
)

MACRO_SIDE_ENDPOINTS = {
    "A": (2, 1),
    "B": (1, 0),
    "C": (0, 3),
    "D": (3, 2),
}
FULL_MACRO_SIDE_CHAINS = {
    "A": ((3, 2, 3), (4, 1, 2), (5, 0, 1)),
    "B": ((5, 1, 2), (5, 2, 3), (6, 1, 2)),
    "C": ((6, 2, 3), (7, 3, 0), (0, 0, 1)),
    "D": (
        (0, 1, 2), (0, 2, 3), (1, 1, 2),
        (2, 0, 1), (2, 1, 2), (2, 2, 3), (3, 1, 2),
    ),
}
MISSING_MACRO_SIDE_CHAINS = {
    **{side: FULL_MACRO_SIDE_CHAINS[side] for side in ("A", "B", "C")},
    # Slot two is absent.  Its complementary C side is the newly exposed
    # boundary arc, represented virtually here only to state its endpoints.
    "D": ((0, 1, 2), (0, 2, 3), (1, 1, 2), (2, 0, 3), (3, 1, 2)),
}


def _check_macro_chain(quad, side, chain):
    children, next_quad = build_level_transforms(quad)
    points = []
    for slot, start_index, end_index in chain:
        points.append((
            _apply(children[slot], quad[start_index]),
            _apply(children[slot], quad[end_index]),
        ))
    parent_start, parent_end = MACRO_SIDE_ENDPOINTS[side]
    return (
        points[0][0] == next_quad[parent_start]
        and points[-1][1] == next_quad[parent_end]
        and all(left[1] == right[0] for left, right in zip(points, points[1:]))
    )


def verify_all_level_macro_side_chains():
    """Prove macro-side endpoint chains on the entire recurrence orbit.

    Every endpoint difference is integer-linear in ``q_n``.  The already
    checked degree-eight matrix annihilator implies the same scalar recurrence
    for each difference, so vanishing on eight consecutive quads proves
    vanishing for every level.
    """
    matrix = recurrence_matrix()
    if any(any(row) for row in matrix_polynomial(matrix, ANNIHILATING_POLYNOMIAL)):
        raise ValueError("cannot lift macro identities without the annihilator")
    quad_vector = flatten_quad(QUAD0)
    checked = []
    for level in range(8):
        quad = unflatten_quad(quad_vector)
        for kind, grammar in (
            ("full", FULL_MACRO_SIDE_CHAINS),
            ("missing", MISSING_MACRO_SIDE_CHAINS),
        ):
            for side, chain in grammar.items():
                if not _check_macro_chain(quad, side, chain):
                    raise ValueError(
                        f"macro-side chain fails at level {level} {kind}/{side}"
                    )
        checked.append(level)
        quad_vector = matrix_vector(matrix, quad_vector)
    return {
        "full_grammar": {
            side: [list(piece) for piece in chain]
            for side, chain in FULL_MACRO_SIDE_CHAINS.items()
        },
        "missing_grammar": {
            side: [list(piece) for piece in chain]
            for side, chain in MISSING_MACRO_SIDE_CHAINS.items()
        },
        "quad_levels_checked": checked,
        "all_level_endpoint_identity": True,
        "missing_slot_two_complement_is_virtual": True,
        "proof": (
            "endpoint differences are linear in q; eight initial zeros plus "
            "the verified degree-8 annihilator prove zero for every level"
        ),
        "proves_boundary_simplicity_or_nonintersection": False,
    }


def predicted_boundary_side_words(max_level: int):
    if max_level < 0:
        raise ValueError("max_level must be nonnegative")
    words = [boundary_side_word(0)]
    if max_level:
        words.append(boundary_side_word(1))
    for level in range(2, max_level + 1):
        pieces = []
        for offset, reverse, mirror, rotation in BOUNDARY_SIDE_RECIPE:
            pieces.extend(transform_direction_word(
                words[level - offset], reverse, mirror, rotation
            ))
        words.append(tuple(pieces))
    return tuple(words)


def boundary_word_recurrence_evidence(max_level: int = 5):
    """Finite falsification gate for the candidate macro-boundary recursion."""
    if max_level < 1:
        raise ValueError("boundary recurrence evidence needs levels zero and one")
    predicted = predicted_boundary_side_words(max_level)
    rows = []
    for level, expected in enumerate(predicted):
        actual = boundary_side_word(level)
        if actual != expected:
            raise ValueError(f"boundary-side recurrence fails at level {level}")
        rows.append({
            "level": level,
            "length": len(actual),
            "sha256": sha256(bytes(actual)).hexdigest(),
        })
    return {
        "maximum_level": max_level,
        "recipe": [list(item) for item in BOUNDARY_SIDE_RECIPE],
        "base_words": [list(predicted[0]), list(predicted[1])],
        "checks": rows,
        "all_equal": True,
        "length_recurrence": "a[n]=4*a[n-1]+a[n-2]",
        "dominant_root": "2+sqrt(5)",
        "inductive_derivation_from_child_gluing": False,
    }
